import type { Metadata } from "next";

import "./globals.css";
import Navbar from './_components/Navbar/navbar';

import { Toaster } from "@/components/ui/sonner"
import CartContextProvider from "@/app/context/cartContext"; // ✅ default import

import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import WishlistContextProvider from "@/app/context/wishlistContext";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en">
      <body>
        <MySessionProvider>
  <CartContextProvider>
    <WishlistContextProvider>
      <Navbar />
      {children}
      <Toaster />
    </WishlistContextProvider>
  </CartContextProvider>
</MySessionProvider>

      </body>
    </html>
  );
}